- hosts: internal
  gather_facts: yes
  become: true
  vars_files:
    - vaulted_vars.yml
  tasks:
  - name: Install the  rpm from a remote repo
    dnf:
      name: "https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm"
      state: present
      disable_gpg_check: true
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
                (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

  - name: Install zabbix-agent
    dnf:
      name: zabbix-agent
      state: present
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
                (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

  - name: Ensure zabbix-agent is started and enabled
    ansible.builtin.systemd:
      name: zabbix-agent
      state: started
      enabled: yes

  - name: Copy zabbix-agent config file
    template: src=/etc/zabbix/zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
    notify: Restart zabbix agent
 
  - ansible.posix.firewalld:
      port: 10050-10051/tcp
      permanent: yes
      immediate: yes
      state: enabled
      zone: docker
   #- name: FirewallD rules
     #ansible.posix.firewalld:
       #permanent: yes
       #immediate: yes
       #port: "{{item.port}}/{{item.proto}}"
       #state: "{{item.state}}"
       #zone: "{{item.zone}}"
     #with_items:
       #- {port: "10050", proto: "tcp", state: "enabled", zone: "docker" }
       #- {port: "10051", proto: "tcp", state: "enabled", zone: "docker" }


  handlers:
    - name: Restart zabbix agent
      ansible.builtin.service:
        name: zabbix-agent
        state: restarted

